-- 在 Supabase SQL Editor 执行一次。不要把 service_role/secret key 放进网页。
create extension if not exists pgcrypto;
create table if not exists public.trip_books (id uuid primary key default gen_random_uuid(),name text not null default '欧洲旅行 2026',invite_code text not null unique,created_by uuid not null references auth.users(id) on delete cascade,created_at timestamptz not null default now());
create table if not exists public.trip_members (trip_id uuid not null references public.trip_books(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,display_name text not null default '旅伴',joined_at timestamptz not null default now(),primary key (trip_id,user_id));
create table if not exists public.shared_expenses (id uuid primary key default gen_random_uuid(),trip_id uuid not null references public.trip_books(id) on delete cascade,created_by uuid not null references auth.users(id) on delete cascade,expense_date date not null default current_date,title text not null,amount numeric(12,2) not null check (amount > 0),currency text not null,payer text not null,category text not null,booking_id text,receipt_path text,receipt_name text,created_at timestamptz not null default now());
alter table public.shared_expenses add column if not exists consumers text[] not null default array['周女士','徐女士'];
alter table public.trip_books enable row level security;
alter table public.trip_members enable row level security;
alter table public.shared_expenses enable row level security;
create or replace function public.is_trip_member(target_trip uuid) returns boolean language sql stable security definer set search_path = public as $$ select exists(select 1 from public.trip_members where trip_id=target_trip and user_id=auth.uid()); $$;
drop policy if exists "members read trips" on public.trip_books;
create policy "members read trips" on public.trip_books for select to authenticated using (public.is_trip_member(id) or created_by=auth.uid());
drop policy if exists "users create trips" on public.trip_books;
create policy "users create trips" on public.trip_books for insert to authenticated with check (created_by=auth.uid());
drop policy if exists "members read membership" on public.trip_members;
create policy "members read membership" on public.trip_members for select to authenticated using (public.is_trip_member(trip_id) or user_id=auth.uid());
drop policy if exists "users join trips" on public.trip_members;
create policy "users join trips" on public.trip_members for insert to authenticated with check (user_id=auth.uid());
create or replace function public.join_trip(requested_code text, display_name text default '旅伴') returns public.trip_books language plpgsql security definer set search_path = public as $$ declare target public.trip_books; begin select * into target from public.trip_books where invite_code=upper(trim(requested_code)); if target.id is null then raise exception '邀请码无效'; end if; insert into public.trip_members(trip_id,user_id,display_name) values(target.id,auth.uid(),coalesce(nullif(trim(display_name),''),'旅伴')) on conflict (trip_id,user_id) do update set display_name=excluded.display_name; return target; end; $$;
grant execute on function public.join_trip(text,text) to authenticated;
create or replace function public.create_trip(trip_name text default '欧洲旅行 2026', display_name text default '我') returns public.trip_books language plpgsql security definer set search_path = public as $$ declare created public.trip_books; code text; begin loop code=upper(substr(encode(gen_random_bytes(5),'hex'),1,6)); exit when not exists(select 1 from public.trip_books where invite_code=code); end loop; insert into public.trip_books(name,invite_code,created_by) values(coalesce(nullif(trim(trip_name),''),'欧洲旅行 2026'),code,auth.uid()) returning * into created; insert into public.trip_members(trip_id,user_id,display_name) values(created.id,auth.uid(),coalesce(nullif(trim(display_name),''),'我')); return created; end; $$;
grant execute on function public.create_trip(text,text) to authenticated;
create or replace function public.ensure_private_trip() returns public.trip_books language plpgsql security definer set search_path = public as $$ declare target public.trip_books; begin select * into target from public.trip_books where invite_code='PRIVATE2026'; if target.id is null then insert into public.trip_books(name,invite_code,created_by) values('欧洲旅行 2026','PRIVATE2026',auth.uid()) returning * into target; end if; insert into public.trip_members(trip_id,user_id,display_name) values(target.id,auth.uid(),coalesce(nullif(split_part(coalesce(auth.jwt()->>'email','旅伴'),'@',1),''),'旅伴')) on conflict (trip_id,user_id) do nothing; return target; end; $$;
grant execute on function public.ensure_private_trip() to authenticated;
drop policy if exists "members read expenses" on public.shared_expenses;
create policy "members read expenses" on public.shared_expenses for select to authenticated using (public.is_trip_member(trip_id));
drop policy if exists "members add expenses" on public.shared_expenses;
create policy "members add expenses" on public.shared_expenses for insert to authenticated with check (public.is_trip_member(trip_id) and created_by=auth.uid());
drop policy if exists "owners update expenses" on public.shared_expenses;
create policy "owners update expenses" on public.shared_expenses for update to authenticated using (created_by=auth.uid()) with check (created_by=auth.uid());
drop policy if exists "owners delete expenses" on public.shared_expenses;
create policy "owners delete expenses" on public.shared_expenses for delete to authenticated using (created_by=auth.uid());
insert into storage.buckets (id,name,public) values ('receipts','receipts',false) on conflict (id) do nothing;
drop policy if exists "members read receipts" on storage.objects;
create policy "members read receipts" on storage.objects for select to authenticated using (bucket_id='receipts' and (storage.foldername(name))[1] in (select trip_id::text from public.trip_members where user_id=auth.uid()));
drop policy if exists "members upload receipts" on storage.objects;
create policy "members upload receipts" on storage.objects for insert to authenticated with check (bucket_id='receipts' and (storage.foldername(name))[1] in (select trip_id::text from public.trip_members where user_id=auth.uid()));
drop policy if exists "members delete receipts" on storage.objects;
create policy "members delete receipts" on storage.objects for delete to authenticated using (bucket_id='receipts' and (storage.foldername(name))[1] in (select trip_id::text from public.trip_members where user_id=auth.uid()));
