import { useCallback, useEffect, useMemo, useState } from 'react'
import { AlertTriangle, BedDouble, Bus, CalendarDays, CarFront, Check, ChevronLeft, ChevronRight, CircleDollarSign, Clock3, ExternalLink, Footprints, House, Landmark, MapPin, Navigation, PackageCheck, PlaneTakeoff, Ship, Square, TicketCheck, TrainFront, Utensils, Wrench, X } from 'lucide-react'
import { bookings, days } from './data'
import type { Activity, Booking, TripDay } from './types'
import TripMap from './TripMap'
import Toolbox from './Toolbox'

type View='overview'|'trip'|'bookings'|'tools';type TripMode='plan'|'day';type Filter='todo'|'all'|'booked'
const nav=[{id:'overview' as View,label:'总览',icon:House},{id:'trip' as View,label:'行程',icon:CalendarDays},{id:'bookings' as View,label:'预订',icon:TicketCheck},{id:'tools' as View,label:'工具',icon:Wrench}]
const colors={train:'#2f6feb',drive:'#087f8c',sight:'#e5484d',food:'#bf8700',hotel:'#7c3aed',note:'#e16f24'}
const icons={train:TrainFront,drive:CarFront,sight:Landmark,food:Utensils,hotel:BedDouble,note:AlertTriangle}
const guide=['舒缓','紧凑','紧凑','紧凑','适中','紧凑','适中','适中','适中','适中','舒缓']

function useStoredSet(key:string){const [set,setSet]=useState<Set<string>>(()=>{try{return new Set(JSON.parse(localStorage.getItem(key)||'[]'))}catch{return new Set()}});useEffect(()=>localStorage.setItem(key,JSON.stringify([...set])),[key,set]);return[set,(id:string)=>setSet(old=>{const next=new Set(old);next.has(id)?next.delete(id):next.add(id);return next})]as const}
function Segment<T extends string>({value,set,items}:{value:T;set:(value:T)=>void;items:{id:T;label:string}[]}){return <div className="segment">{items.map(item=><button className={value===item.id?'active':''} onClick={()=>set(item.id)} key={item.id}>{item.label}</button>)}</div>}

function Sheet({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <><button className="sheet-scrim" aria-label="关闭详情" onClick={onClose}/><aside className="detail-sheet"><header><h2>{title}</h2><button onClick={onClose} aria-label="关闭"><X/></button></header>{children}</aside></>}

function ActivityIcon({item}:{item:Activity}){const Icon=icons[item.kind];return <span className="type-icon" style={{'--type':colors[item.kind]} as React.CSSProperties}><Icon/></span>}
function tags(item:Activity){return [item.booked?'已确认':'',item.cost||'',item.important?'重点':''].filter(Boolean)}

function CompactActivity({item,index,active,done,onSelect,onDone}:{item:Activity;index:number;active:boolean;done:boolean;onSelect:()=>void;onDone:()=>void}){return <article className={`compact-activity activity-${item.kind} ${active?'active':''} ${done?'done':''}`} style={{'--activity':colors[item.kind]} as React.CSSProperties} onClick={onSelect}><button className="activity-check" onClick={event=>{event.stopPropagation();onDone()}}>{done?<Check/>:<span>{index+1}</span>}</button><ActivityIcon item={item}/><time>{item.time}</time><div><h3>{item.title}</h3><p>{item.detail}</p></div><footer>{tags(item).slice(0,2).map(tag=><span key={tag}>{tag}</span>)}</footer></article>}

function ActivitySheet({item,day,onClose}:{item:Activity;day:TripDay;onClose:()=>void}){const point=`${item.title} ${day.city}`;return <Sheet title={item.title} onClose={onClose}><div className="sheet-type"><ActivityIcon item={item}/><div><span>{item.time}</span><b>{day.date} · {day.city}</b></div></div><p className="sheet-detail">{item.detail}</p><div className="chip-row">{tags(item).map(tag=><span key={tag}>{tag}</span>)}</div><a className="sheet-primary" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(point)}`} target="_blank" rel="noreferrer"><MapPin/>在地图中打开</a></Sheet>}

function Dashboard({go}:{go:(view:View)=>void}){const urgent=bookings.filter(item=>item.status==='urgent').length;const booked=bookings.filter(item=>item.status==='booked').length;return <div className="dashboard"><header className="context-heading journey-heading"><div><span>9月25日启程 · 欧洲三国</span><h1>荷德奥旅游手账</h1><small>Amsterdam → Vienna · 11天</small></div><div className="travel-stamp" aria-hidden="true">EUROPE<b>2026</b></div><button onClick={()=>go('trip')}>打开行程 <ChevronRight/></button></header><div className="dashboard-grid"><section className="dash-map"><TripMap dayId="d3" onSelect={()=>{}}/></section><aside className="dash-side"><div className="mini-stats"><button onClick={()=>go('bookings')}><PackageCheck/><b>{booked}/{bookings.length}</b><span>准备进度</span></button><button onClick={()=>go('bookings')} className="warn"><AlertTriangle/><b>{urgent}</b><span>立即处理</span></button><button onClick={()=>go('tools')}><CircleDollarSign/><b>待报价</b><span>预算参考</span></button><button onClick={()=>go('trip')}><CalendarDays/><b>11天</b><span>完整日程</span></button></div><section className="next-panel"><header><TrainFront/><span>下一段已购交通</span></header><div><time>21:01</time><b>Amsterdam Centraal</b><i/></div><div><time>23:45</time><b>Köln Hbf</b></div><small>9月27日 · IC 60403 · 直达自由座</small></section><section className="quick-tasks"><h2>出发前要紧事</h2>{bookings.filter(item=>item.status==='urgent').slice(0,3).map(item=><button onClick={()=>go('bookings')} key={item.id}><AlertTriangle/><span><b>{item.title}</b><small>{item.date}</small></span><ChevronRight/></button>)}</section></aside></div></div>}

function PlanList({open}:{open:(index:number)=>void}){return <div className="compact-plan">{days.map((day,index)=><button onClick={()=>open(index)} key={day.id}><span className={`day-dot country-${day.country}`}>D{day.day}</span><time>{day.date}<small>{day.weekday}</small></time><div><b>{day.title}</b><span>{day.city} · {day.activities.length}项</span></div><em className={`density density-${guide[index]}`}>{guide[index]}</em><ChevronRight/></button>)}</div>}

function TripPage(){const [mode,setMode]=useState<TripMode>('day');const [index,setIndex]=useState(0);const [active,setActive]=useState<string>();const [detail,setDetail]=useState<Activity>();const [done,toggle]=useStoredSet('travel-activity-done');const day=days[index];const select=useCallback((id:string)=>{setActive(id);document.getElementById(`activity-${id}`)?.scrollIntoView({behavior:'smooth',block:'nearest'})},[]);const openPlan=(next:number)=>{setIndex(next);setActive(undefined);setMode('day')};return <div className={`trip-workspace theme-${day.country}`}><header className="context-bar trip-heading"><div className="day-nav"><button disabled={index===0} onClick={()=>setIndex(value=>value-1)}><ChevronLeft/></button><div><span>DAY {day.day} · {day.date} · {day.weekday}</span><b>{day.city}</b></div><button disabled={index===days.length-1} onClick={()=>setIndex(value=>value+1)}><ChevronRight/></button></div><Segment value={mode} set={setMode} items={[{id:'day',label:'单日'},{id:'plan',label:'全程'}]}/></header>{mode==='plan'?<PlanList open={openPlan}/>:<div className="map-list-layout"><TripMap dayId={day.id} activeId={active} onSelect={select}/><section className="activity-pane"><header><div><small className="journal-kicker">TODAY'S NOTES</small><b>{day.title}</b><span><BedDouble/> {day.hotel}</span></div><em className={`density density-${guide[index]}`}>{guide[index]}</em></header>{day.note&&<div className="compact-notice"><AlertTriangle/>{day.note}</div>}<div className="activity-scroll">{day.activities.map((item,itemIndex)=><div id={`activity-${item.id}`} key={item.id}><CompactActivity item={item} index={itemIndex} active={active===item.id} done={done.has(item.id)} onSelect={()=>{setActive(item.id);setDetail(item)}} onDone={()=>toggle(item.id)}/></div>)}</div></section></div>}{detail&&<ActivitySheet item={detail} day={day} onClose={()=>setDetail(undefined)}/>}</div>}

function bookingType(item:Booking){if(/Hotel|Holiday|Hilton|Moxy|住宿|DoubleTree/.test(item.title))return['住宿',BedDouble,'#7c3aed']as const;if(/租车|驾照|翻译件|自驾/.test(item.title))return['自驾',CarFront,'#087f8c']as const;if(/→|日票|Westbahn|IC |火车/.test(item.title))return['交通',TrainFront,'#2f6feb']as const;return['景点',Landmark,'#e5484d']as const}
function bookingStatus(item:Booking,done:boolean){if(done)return['已完成','done']as const;if(item.status==='booked')return['已确认','booked']as const;if(item.status==='urgent')return['尽快预订','urgent']as const;return['待安排','pending']as const}
function BookingSheet({item,onClose}:{item:Booking;onClose:()=>void}){const [type,Icon,color]=bookingType(item);return <Sheet title={item.title} onClose={onClose}><div className="sheet-type"><span className="type-icon" style={{'--type':color} as React.CSSProperties}><Icon/></span><div><span>{type} · {item.date}</span><b>{item.price}</b></div></div><p className="sheet-detail">{item.detail}</p>{item.url&&<a className="sheet-primary" href={item.url} target="_blank" rel="noreferrer"><ExternalLink/>打开官方网站</a>}</Sheet>}
function BookingsPage(){const [filter,setFilter]=useState<Filter>('todo');const [selected,setSelected]=useState<Booking>();const [done,toggle]=useStoredSet('travel-bookings-done');const list=bookings.filter(item=>filter==='all'||(filter==='booked'?item.status==='booked':item.status!=='booked'&&!done.has(item.id)));return <div className="list-workspace"><header className="context-bar"><div><span>交通 · 住宿 · 景点</span><b>预订与准备</b></div><Segment value={filter} set={setFilter} items={[{id:'todo',label:'待办'},{id:'all',label:'全部'},{id:'booked',label:'已确认'}]}/></header><div className="booking-compact">{list.map(item=>{const [type,Icon,color]=bookingType(item);const isBooked=item.status==='booked';const isDone=!isBooked&&done.has(item.id);const [status,statusTone]=bookingStatus(item,isDone);return <article className={isBooked?'is-booked':isDone?'is-done':''} key={item.id} onClick={()=>setSelected(item)}>{isBooked?<span className="booking-state confirmed" aria-label={`已确认：${item.title}`} title="订单已确认"><TicketCheck/></span>:<button className="booking-state row-check" aria-label={`${isDone?'取消完成':'标记完成'}：${item.title}`} aria-pressed={isDone} title={isDone?'取消完成':'标记完成'} onClick={event=>{event.stopPropagation();toggle(item.id)}}>{isDone?<Check/>:<Square/>}</button>}<span className="type-icon" style={{'--type':color} as React.CSSProperties}><Icon/></span><time>{item.date}</time><div className="booking-copy"><b>{item.title}</b><small><span>{type}</span>{item.detail}</small></div><div className="booking-meta"><span className={`status-pill status-${statusTone}`}>{status}</span><strong>{item.price}</strong></div><ChevronRight/></article>})}</div>{selected&&<BookingSheet item={selected} onClose={()=>setSelected(undefined)}/>}</div>}

function ToolsPage(){return <Toolbox/>}

export default function App(){const legacy:Record<string,View>={days:'trip',route:'trip',budget:'tools'};const raw=location.hash.replace('#/','')||'overview';const initial=(legacy[raw]||raw)as View;const [view,setView]=useState<View>(nav.some(item=>item.id===initial)?initial:'overview');const go=(next:View)=>{setView(next);history.pushState(null,'',`#/${next}`)};useEffect(()=>{const handler=()=>{const value=location.hash.replace('#/','')||'overview';setView((legacy[value]||value)as View)};addEventListener('hashchange',handler);return()=>removeEventListener('hashchange',handler)},[]);const page=useMemo(()=>view==='overview'?<Dashboard go={go}/>:view==='trip'?<TripPage/>:view==='bookings'?<BookingsPage/>:<ToolsPage/>,[view]);return <div className="app-frame"><aside className="side-nav"><button className="app-logo" onClick={()=>go('overview')}><Navigation/><span>荷德奥<b>TRAVEL 2026</b></span></button><nav>{nav.map(item=>{const Icon=item.icon;return <button className={view===item.id?'active':''} onClick={()=>go(item.id)} key={item.id}><Icon/><span>{item.label}</span></button>})}</nav><div className="departure"><PlaneTakeoff/><span>9月25日出发</span></div></aside><main className="app-main">{page}</main><nav className="mobile-nav">{nav.map(item=>{const Icon=item.icon;return <button className={view===item.id?'active':''} onClick={()=>go(item.id)} key={item.id}><Icon/><span>{item.label}</span></button>})}</nav></div>}
