import { useEffect, useMemo, useState } from 'react'
import { AlertTriangle, Check, ChevronLeft, CircleDollarSign, CloudSun, Copy, ExternalLink, Languages, Luggage, Search, ShieldCheck, ShoppingBag, Smartphone, Stethoscope } from 'lucide-react'
import ExpenseLedger from './ExpenseLedger'
import { apps, glossary, packing, quickInfo, risks, shopping, visaGroups } from './toolboxData'
type Tool='home'|'expense'|'packing'|'visa'|'quick'|'apps'|'language'|'shopping'|'risks'
const tools=[['expense','费用分账',CircleDollarSign,'#27866b'],['packing','行李清单',Luggage,'#2f6feb'],['visa','签证材料',ShieldCheck,'#7c3aed'],['quick','应急速查',Stethoscope,'#e5484d'],['apps','常用App',Smartphone,'#0891b2'],['language','地名语言',Languages,'#8250df'],['shopping','购物退税',ShoppingBag,'#bf8700'],['risks','行程风险',AlertTriangle,'#e16f24']]as const
const loadDone=()=>{try{return new Set<string>(JSON.parse(localStorage.getItem('travel-tool-done')||'[]'))}catch{return new Set<string>()}}
export default function Toolbox(){const [tool,setTool]=useState<Tool>('home');const [done,setDone]=useState(loadDone);const [query,setQuery]=useState('');const [copied,setCopied]=useState('');useEffect(()=>localStorage.setItem('travel-tool-done',JSON.stringify([...done])),[done]);const toggle=(id:string)=>setDone(old=>{const next=new Set(old);next.has(id)?next.delete(id):next.add(id);return next});const words=useMemo(()=>glossary.filter(item=>item.join(' ').toLowerCase().includes(query.toLowerCase())),[query]);const copy=async(text:string)=>{await navigator.clipboard.writeText(text);setCopied(text);setTimeout(()=>setCopied(''),1000)}
 if(tool==='home')return <div className="tool-workspace"><header className="context-bar"><div><span>随身资料与记录</span><b>工具</b></div></header><div className="tool-tile-grid">{tools.map(([id,label,Icon,color])=><button onClick={()=>setTool(id)} key={id}><span style={{'--tool':color} as React.CSSProperties}><Icon/></span><b>{label}</b><small>{id==='expense'?'预算、消费与结算':id==='packing'?'出发前逐项勾选':id==='quick'?'天气、电话、支付':id==='risks'?'高风险优先查看':'点击查看详情'}</small></button>)}</div><section className="tool-glance"><CloudSun/><div><b>九月底天气</b><span>约7–19°C · 多风阵雨 · 分层穿衣</span></div><button onClick={()=>setTool('quick')}>查看</button></section></div>
 const title=tools.find(item=>item[0]===tool)?.[1]||'工具';return <div className="tool-workspace"><header className="context-bar tool-context"><button onClick={()=>setTool('home')}><ChevronLeft/></button><div><span>工具</span><b>{title}</b></div></header><div className="tool-panel">
 {tool==='expense'&&<><div className="budget-mini"><article><span>两人可变支出</span><b>€975–1,150</b></article><article><span>交通</span><b>约€180</b></article><article><span>景点</span><b>约€245</b></article><article><span>餐饮</span><b>约€550</b></article></div><ExpenseLedger/></>}
 {tool==='quick'&&<div className="info-compact">{quickInfo.map(group=><article key={group.title}><h3>{group.title}</h3>{group.items.map(item=><p key={item}>{item}</p>)}</article>)}</div>}
 {tool==='packing'&&<CheckGroups groups={packing.map(group=>({title:group.group,items:group.items,prefix:'pack'}))} done={done} toggle={toggle}/>}
 {tool==='visa'&&<CheckGroups groups={visaGroups.map(group=>({title:group.title,items:group.items,prefix:'visa'}))} done={done} toggle={toggle}/>}
 {tool==='apps'&&<div className="app-compact">{apps.map(item=><a href={item[2]} target="_blank" rel="noreferrer" key={item[0]}><span>{item[0].slice(0,2)}</span><div><b>{item[0]}</b><small>{item[1]}</small></div><ExternalLink/></a>)}</div>}
 {tool==='language'&&<><label className="tool-search"><Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="搜索地点或德语"/></label><div className="language-compact">{words.map(item=><article key={item[0]}><span>{item[2]}</span><div><b>{item[0]}</b><small>{item[1]}</small></div><button onClick={()=>copy(item[1])}>{copied===item[1]?<Check/>:<Copy/>}</button></article>)}</div></>}
 {tool==='shopping'&&<div className="info-compact shopping">{shopping.map(group=><article key={group.city}><h3>{group.city}</h3>{group.items.map(item=><p key={item}>{item}</p>)}</article>)}</div>}
 {tool==='risks'&&<div className="risk-compact">{risks.map((risk,index)=><article key={risk[1]} className={`risk-${risk[0]}`}><span>{risk[0]}</span><div><b>{risk[1]}</b><p>{risk[2]}</p></div><em>{index+1}</em></article>)}</div>}
 </div></div>}
function CheckGroups({groups,done,toggle}:{groups:{title:string;items:string[];prefix:string}[];done:Set<string>;toggle:(id:string)=>void}){return <div className="check-compact">{groups.map(group=><section key={group.title}><header><b>{group.title}</b><span>{group.items.filter((_,index)=>done.has(`${group.prefix}-${group.title}-${index}`)).length}/{group.items.length}</span></header>{group.items.map((item,index)=>{const id=`${group.prefix}-${group.title}-${index}`;return <button className={done.has(id)?'done':''} onClick={()=>toggle(id)} key={item}><span>{done.has(id)&&<Check/>}</span>{item}</button>})}</section>)}</div>}
