export const quickInfo = [
  {title:'九月底天气',items:['阿姆斯特丹约11–18°C，多风多阵雨','科隆与慕尼黑约9–18°C，早晚偏凉','萨尔茨堡湖区约7–17°C，山区体感更低','维也纳约10–19°C；以临行前7天预报为准','穿衣建议：速干内层＋保暖中层＋防水外壳']},
  {title:'紧急号码',items:['欧盟通用急救/报警：112','荷兰警察非紧急：0900-8844','德国警察：110 · 急救/消防：112','奥地利警察：133 · 急救：144']},
  {title:'支付与现金',items:['银行卡/Apple Pay覆盖度高，仍备€100–150现金','荷兰部分小店偏好本地借记卡，先看Visa/Mastercard标识','德国啤酒屋、市场及储物柜可能需要现金','奥地利餐厅结账时主动告知小费后的总金额']},
  {title:'小费习惯',items:['荷兰餐厅服务好可给5–10%，非强制','德国餐厅通常凑整或给5–10%','奥地利餐厅约5–10%，报总额而非把零钱留桌上','酒店行李员：€1–2/件']},
  {title:'网络与插座',items:['三国均使用欧标Type C/F，电压230V','中国两脚扁插通常需要转换头','建议购买欧盟通用eSIM，提前下载离线地图','跨城列车Wi-Fi不稳定，车票截图离线保存']},
  {title:'奥地利自驾',items:['随车携带中国驾照原件及租车公司书面认可的德语翻译件','取车时拍摄全车、轮胎、油表并核对保险自付额','用ASFINAG按车牌核验高速票，租车已含时不要重复购买','哈尔施塔特古城禁车，P1/P2不可预约，目标08:15前进入','戈绍湖停车场车牌识别缴费且禁止过夜','10月湖区可能雨雾早霜，避免摸黑走山路']},
  {title:'安全与健康',items:['中央站、地铁和热门景点注意手机与钱包','护照原件贴身，云端另存证件与保单副本','随身备止泻、感冒、胃药及个人常用药','饮用水通常安全；餐厅自来水不一定免费']},
  {title:'退税',items:['满足单店最低消费后向商户索取退税单','离开欧盟时在维也纳机场先海关验货盖章','托运行李中的退税商品要在托运前办理海关','再到Global Blue或Planet柜台退款']},
]

export const packing = [
  {group:'证件与票据',items:['护照及申根签证','旅行保险英文保单','机票、火车票离线截图','酒店确认单','中国驾照原件及认可德语翻译件','主驾驶实体信用卡','银行卡2张分开放','少量欧元现金']},
  {group:'衣物',items:['防水轻薄外套','针织衫/抓绒中层','长裤2–3条','舒适防滑步行鞋','轻便手套与薄围巾','折叠伞']},
  {group:'电子设备',items:['手机与充电线','欧标转换插头','充电宝（随身携带）','eSIM/漫游方案','耳机','备用数据线']},
  {group:'随身小包',items:['纸巾与湿巾','水杯','常用药','创可贴','小袋零食','酒店名片/地址截图']},
]

export const apps = [
  {name:'Google Maps',category:'地图与交通',description:'全程地图、公交与步行导航',url:'https://www.google.com/maps/?api=1',iosScheme:'comgooglemaps://',ios:'https://apps.apple.com/app/google-maps/id585027354',android:'https://play.google.com/store/apps/details?id=com.google.android.apps.maps',icon:'app-icons/google-maps.png',fallback:'GM'},
  {name:'NS',category:'地图与交通',description:'荷兰火车实时班次',url:'https://www.ns.nl/en',ios:'https://apps.apple.com/app/ns-travel-planner/id370362301',android:'https://play.google.com/store/apps/details?id=nl.ns.android.activity',icon:'app-icons/ns.png',fallback:'NS'},
  {name:'9292',category:'地图与交通',description:'荷兰综合公共交通',url:'https://9292.nl/en',ios:'https://apps.apple.com/app/9292-travel-planner-e-ticket/id556557690',android:'https://play.google.com/store/apps/details?id=nl.negentwee',icon:'app-icons/9292.png',fallback:'92'},
  {name:'DB Navigator',category:'地图与交通',description:'德国铁路、站台和延误',url:'https://int.bahn.de/en',ios:'https://apps.apple.com/app/db-navigator/id343555245',android:'https://play.google.com/store/apps/details?id=de.hafas.android.db',icon:'app-icons/db-navigator.png',fallback:'DB'},
  {name:'MVV-App',category:'地图与交通',description:'慕尼黑市内交通',url:'https://www.mvv-muenchen.de/en',ios:'https://apps.apple.com/app/mvv-app/id388686726',android:'https://play.google.com/store/apps/details?id=com.mdv.companion',icon:'app-icons/mvv.png',fallback:'MV'},
  {name:'ÖBB',category:'地图与交通',description:'奥地利铁路及林茨至维也纳车票',url:'https://www.oebb.at/en/',ios:'https://apps.apple.com/app/%C3%B6bb-tickets/id1041401604',android:'https://play.google.com/store/apps/details?id=at.oebb.ts',icon:'app-icons/oebb.png',fallback:'ÖB'},
  {name:'ASFINAG',category:'地图与交通',description:'奥地利高速票车牌查询与路况',url:'https://www.asfinag.at/en/',ios:'https://apps.apple.com/app/asfinag/id453459323',android:'https://play.google.com/store/apps/details?id=at.asfinag.unterwegs',icon:'app-icons/asfinag.png',fallback:'AS'},
  {name:'WienMobil',category:'地图与交通',description:'维也纳公共交通',url:'https://www.wienerlinien.at/web/wl-en',ios:'https://apps.apple.com/app/wienmobil/id1107918142',android:'https://play.google.com/store/apps/details?id=at.wienerlinien.wienmobillab',icon:'app-icons/wienmobil.png',fallback:'WM'},
  {name:'Google Translate',category:'语言沟通',description:'菜单与现场沟通',url:'https://translate.google.com',ios:'https://apps.apple.com/app/google-translate/id414706506',android:'https://play.google.com/store/apps/details?id=com.google.android.apps.translate',icon:'app-icons/google-translate.png',fallback:'GT'},
  {name:'DeepL',category:'语言沟通',description:'德语长句翻译',url:'https://www.deepl.com',ios:'https://apps.apple.com/app/deepl-translate/id1552407475',android:'https://play.google.com/store/apps/details?id=com.deepl.mobiletranslator',icon:'app-icons/deepl.png',fallback:'DL'},
  {name:'Global Blue',category:'旅行服务',description:'退税进度查询',url:'https://www.globalblue.com/',ios:'https://apps.apple.com/app/global-blue-shop-tax-free/id693120896',android:'https://play.google.com/store/apps/details?id=com.buuuk.globalblue',icon:'app-icons/global-blue.ico',fallback:'GB'},
  {name:'Splitwise',category:'旅行服务',description:'额外的多人分账备份',url:'https://www.splitwise.com/',ios:'https://apps.apple.com/app/splitwise/id458023433',android:'https://play.google.com/store/apps/details?id=com.Splitwise.SplitwiseMobile',icon:'app-icons/splitwise.png',fallback:'SW'},
]

export const shopping = [
  {city:'阿姆斯特丹',items:['Tony’s Chocolonely巧克力','荷兰奶酪（真空包装）','Royal Delft蓝陶小件','HEMA设计文具','郁金香主题纪念品（注意入境植物限制）']},
  {city:'科隆',items:['4711古龙水旅行装','科隆大教堂纪念品','Kölsch细长啤酒杯','当地巧克力']},
  {city:'慕尼黑',items:['啤酒节纪念杯与徽章','Haribo限定口味','巴伐利亚传统小饰品','Dallmayr咖啡与茶']},
  {city:'萨尔茨堡',items:['莫扎特巧克力球','Zaunerstollen杏仁糕','岩盐制品','《音乐之声》纪念品']},
  {city:'维也纳',items:['Manner威化','Demel/Sacher甜点礼盒','Julius Meinl咖啡','奥地利水晶或博物馆文创']},
]

export const glossary = [
  {zh:'阿姆斯特丹',local:'Amsterdam',english:'Amsterdam',country:'NL',category:'城市'},
  {zh:'史基浦机场',local:'Luchthaven Schiphol',english:'Amsterdam Airport Schiphol',country:'NL',category:'机场'},
  {zh:'阿姆斯特丹斯洛特戴克站',local:'Station Amsterdam Sloterdijk',english:'Amsterdam Sloterdijk Station',country:'NL',category:'车站'},
  {zh:'阿姆斯特丹中央站',local:'Amsterdam Centraal',english:'Amsterdam Central Station',country:'NL',category:'车站'},
  {zh:'斯滕韦克',local:'Steenwijk',english:'Steenwijk',country:'NL',category:'城市'},
  {zh:'羊角村',local:'Giethoorn',english:'Giethoorn',country:'NL',category:'景点'},
  {zh:'九街',local:'De 9 Straatjes',english:'The Nine Streets',country:'NL',category:'街区'},
  {zh:'安妮之家',local:'Anne Frank Huis',english:'Anne Frank House',country:'NL',category:'景点'},
  {zh:'梵高博物馆',local:'Van Gogh Museum',english:'Van Gogh Museum',country:'NL',category:'博物馆'},
  {zh:'荷兰国立博物馆',local:'Rijksmuseum',english:'Rijksmuseum',country:'NL',category:'博物馆'},
  {zh:'约旦区',local:'Jordaan',english:'Jordaan',country:'NL',category:'街区'},
  {zh:'阿姆斯特丹斯洛特戴克智选假日酒店',local:'Holiday Inn Express Amsterdam – Sloterdijk',english:'Holiday Inn Express Amsterdam – Sloterdijk',country:'NL',category:'住宿'},

  {zh:'科隆',local:'Köln',english:'Cologne',country:'DE',category:'城市'},
  {zh:'科隆中央站',local:'Köln Hauptbahnhof / Köln Hbf',english:'Cologne Central Station',country:'DE',category:'车站'},
  {zh:'科隆大教堂',local:'Kölner Dom',english:'Cologne Cathedral',country:'DE',category:'景点'},
  {zh:'霍亨索伦大桥',local:'Hohenzollernbrücke',english:'Hohenzollern Bridge',country:'DE',category:'景点'},
  {zh:'莱茵河',local:'Rhein',english:'Rhine River',country:'DE',category:'地标'},
  {zh:'科隆老城',local:'Kölner Altstadt',english:'Cologne Old Town',country:'DE',category:'街区'},
  {zh:'路德维希博物馆',local:'Museum Ludwig',english:'Museum Ludwig',country:'DE',category:'博物馆'},
  {zh:'科隆希尔顿酒店',local:'Hilton Köln',english:'Hilton Cologne',country:'DE',category:'住宿'},
  {zh:'慕尼黑',local:'München',english:'Munich',country:'DE',category:'城市'},
  {zh:'慕尼黑东站',local:'München Ostbahnhof',english:'Munich East Station',country:'DE',category:'车站'},
  {zh:'慕尼黑中央站',local:'München Hauptbahnhof / München Hbf',english:'Munich Central Station',country:'DE',category:'车站'},
  {zh:'玛利亚广场',local:'Marienplatz',english:'Marienplatz',country:'DE',category:'景点'},
  {zh:'新市政厅钟琴',local:'Rathaus-Glockenspiel',english:'New Town Hall Glockenspiel',country:'DE',category:'景点'},
  {zh:'慕尼黑圣母教堂',local:'Frauenkirche München',english:'Munich Cathedral',country:'DE',category:'景点'},
  {zh:'维克图阿连市场',local:'Viktualienmarkt',english:'Viktualienmarkt Food Market',country:'DE',category:'市场'},
  {zh:'慕尼黑皇宫与珍宝馆',local:'Münchner Residenz und Schatzkammer',english:'Munich Residenz and Treasury',country:'DE',category:'景点'},
  {zh:'英国花园',local:'Englischer Garten',english:'English Garden',country:'DE',category:'公园'},
  {zh:'艾斯巴赫冲浪点',local:'Eisbachwelle',english:'Eisbach Wave',country:'DE',category:'景点'},
  {zh:'慕尼黑皇家啤酒屋',local:'Hofbräuhaus München',english:'Hofbräuhaus Munich',country:'DE',category:'餐厅'},
  {zh:'慕尼黑啤酒节／特蕾西娅草坪',local:'Oktoberfest / Theresienwiese',english:'Oktoberfest / Theresienwiese',country:'DE',category:'活动'},
  {zh:'慕尼黑东站慕奇夕酒店',local:'Moxy München Ostbahnhof',english:'Moxy Munich Ostbahnhof',country:'DE',category:'住宿'},
  {zh:'菲森',local:'Füssen',english:'Fussen',country:'DE',category:'城市'},
  {zh:'新天鹅堡',local:'Schloss Neuschwanstein',english:'Neuschwanstein Castle',country:'DE',category:'景点'},
  {zh:'玛丽安桥',local:'Marienbrücke',english:"Mary's Bridge",country:'DE',category:'景点'},

  {zh:'萨尔茨堡',local:'Salzburg',english:'Salzburg',country:'AT',category:'城市'},
  {zh:'霍亨萨尔茨堡要塞',local:'Festung Hohensalzburg',english:'Hohensalzburg Fortress',country:'AT',category:'景点'},
  {zh:'莫扎特出生地',local:'Mozarts Geburtshaus',english:"Mozart's Birthplace",country:'AT',category:'景点'},
  {zh:'萨尔茨堡老城',local:'Salzburger Altstadt',english:'Salzburg Old Town',country:'AT',category:'街区'},
  {zh:'粮食胡同',local:'Getreidegasse',english:'Getreidegasse',country:'AT',category:'街区'},
  {zh:'蒙德湖镇／蒙德湖',local:'Mondsee',english:'Mondsee / Lake Mondsee',country:'AT',category:'湖区'},
  {zh:'蒙德湖圣米歇尔大教堂',local:'Basilika St. Michael Mondsee',english:'Basilica of St. Michael, Mondsee',country:'AT',category:'景点'},
  {zh:'圣吉尔根',local:'St. Gilgen',english:'St Gilgen',country:'AT',category:'城市'},
  {zh:'沃尔夫冈湖',local:'Wolfgangsee',english:'Lake Wolfgang',country:'AT',category:'湖区'},
  {zh:'圣沃尔夫冈',local:'St. Wolfgang im Salzkammergut',english:'St Wolfgang im Salzkammergut',country:'AT',category:'城市'},
  {zh:'哈尔施塔特',local:'Hallstatt',english:'Hallstatt',country:'AT',category:'城市'},
  {zh:'哈尔施塔特P1／P2停车场',local:'Parkplatz P1 / P2 Hallstatt',english:'Hallstatt P1 / P2 Parking',country:'AT',category:'停车'},
  {zh:'哈尔施塔特市场广场',local:'Marktplatz Hallstatt',english:'Hallstatt Market Square',country:'AT',category:'景点'},
  {zh:'哈尔施塔特骨屋',local:'Beinhaus Hallstatt',english:'Hallstatt Bone House',country:'AT',category:'景点'},
  {zh:'前戈绍湖',local:'Vorderer Gosausee',english:'Lake Gosau / Vorderer Gosausee',country:'AT',category:'湖区'},
  {zh:'戈绍',local:'Gosau',english:'Gosau',country:'AT',category:'城市'},
  {zh:'巴德戈伊瑟恩',local:'Bad Goisern am Hallstättersee',english:'Bad Goisern on Lake Hallstatt',country:'AT',category:'城市'},
  {zh:'阿尔陶斯',local:'Altaussee',english:'Altaussee',country:'AT',category:'城市'},
  {zh:'阿尔陶斯湖',local:'Altausseer See',english:'Lake Altaussee',country:'AT',category:'湖区'},
  {zh:'格伦德尔湖',local:'Grundlsee',english:'Lake Grundlsee',country:'AT',category:'湖区'},
  {zh:'特劳恩湖',local:'Traunsee',english:'Lake Traunsee',country:'AT',category:'湖区'},
  {zh:'特劳恩基兴',local:'Traunkirchen',english:'Traunkirchen',country:'AT',category:'城市'},
  {zh:'格蒙登',local:'Gmunden',english:'Gmunden',country:'AT',category:'城市'},
  {zh:'奥尔特城堡',local:'Seeschloss Ort',english:'Ort Castle',country:'AT',category:'景点'},
  {zh:'林茨',local:'Linz',english:'Linz',country:'AT',category:'城市'},
  {zh:'林茨中央站',local:'Linz Hauptbahnhof / Linz Hbf',english:'Linz Central Station',country:'AT',category:'车站'},
  {zh:'维也纳',local:'Wien',english:'Vienna',country:'AT',category:'城市'},
  {zh:'维也纳中央站',local:'Wien Hauptbahnhof / Wien Hbf',english:'Vienna Central Station',country:'AT',category:'车站'},
  {zh:'维也纳艺术史博物馆',local:'Kunsthistorisches Museum Wien',english:'Kunsthistorisches Museum Vienna',country:'AT',category:'博物馆'},
  {zh:'格拉本大街',local:'Graben',english:'Graben',country:'AT',category:'街区'},
  {zh:'圣史蒂芬大教堂',local:'Stephansdom',english:"St. Stephen's Cathedral",country:'AT',category:'景点'},
  {zh:'美泉宫',local:'Schloss Schönbrunn',english:'Schönbrunn Palace',country:'AT',category:'景点'},
  {zh:'维也纳美泉宫希尔顿逸林酒店',local:'DoubleTree by Hilton Vienna Schönbrunn',english:'DoubleTree by Hilton Vienna Schönbrunn',country:'AT',category:'住宿'},
  {zh:'维也纳国际机场',local:'Flughafen Wien-Schwechat',english:'Vienna International Airport',country:'AT',category:'机场'},

  {zh:'中央火车站',local:'Hauptbahnhof / Hbf',english:'Central Station',country:'DE',category:'交通'},
  {zh:'站台',local:'Gleis',english:'Platform',country:'DE',category:'交通'},
  {zh:'换乘',local:'Umsteigen',english:'Transfer / Change trains',country:'DE',category:'交通'},
  {zh:'行李寄存柜',local:'Schließfach',english:'Luggage locker',country:'DE',category:'交通'},
  {zh:'特价票',local:'Super Sparpreis',english:'Super saver fare',country:'DE',category:'交通'},
  {zh:'区域列车',local:'Regionalbahn / Regional-Express',english:'Regional train',country:'DE',category:'交通'},
  {zh:'请问站台在哪里？',local:'Wo ist das Gleis?',english:'Where is the platform?',country:'DE',category:'应急'},
  {zh:'这班车去……吗？',local:'Fährt dieser Zug nach …?',english:'Does this train go to …?',country:'DE',category:'应急'},
  {zh:'请结账',local:'Zahlen, bitte.',english:'The bill, please.',country:'DE',category:'餐厅'},
  {zh:'不要再续杯',local:'Bitte nicht mehr.',english:'No more, please.',country:'DE',category:'餐厅'},
]

export const risks = [
  ['高','新天鹅堡时段必须预约','持14天套票仍需选择Multi-Day Ticket Holder并支付预约费。'],['高','9/28科隆至慕尼黑换乘2次','当天持续查看DB App；前序延误时保留原票并按DB指引改乘。'],['高','9/30行李必须寄存在慕尼黑Hbf','不要留在Moxy，否则新天鹅堡返程后无法顺路赶萨尔茨堡。'],['中','D1羊角村接安妮之家','返程延误就取消九街，安妮之家预约优先。'],['中','D2取行李到发车缓冲有限','19:50开始返回中央站，最迟20:15取到行李。'],['中','慕尼黑至萨尔茨堡票种限制','拜仁日票只覆盖区域列车，不含Railjet和ICE。'],['中','Moxy两晚是两个订单','首次入住时请前台关联，尽量原房续住。'],
  ['高','中国驾照材料必须书面确认','携带中国驾照原件；订车前让租车公司书面接受具体德语翻译件。'],['高','10/4周日林茨异地还车','门店营业、钥匙箱、验车和异地还车必须写入订单或邮件确认。'],['中','哈尔施塔特停车不可预约','古城禁车，P1/P2看电子余位，10/2目标08:15前抵达。'],['中','湖区雨雾与早霜','每日查天气；低能见度时取消湖畔徒步和山路支线，不夜间赶路。'],['中','高速票按车牌核验','取车时用ASFINAG确认Vignette有效，已有时不要重复购买。'],['中','哈尔施塔特盐矿复开时间','2026夏季计划重开但日期未锁定，只作为可选项，临行复核。'],['低','连续三晚更换住宿','每天退房前清点行李，不把护照、药品和电子设备留车内。'],['低','维也纳返程日不要再绕市区','13:30取行李，15:00直接前往机场。'],
]

export const visaGroups = [
  {title:'身份与申请',items:['德国申根签证申请表并签字','护照原件及资料页/签证页复印件','旧护照（如有）','身份证和户口簿复印件','近期35×45mm白底照片×2']},
  {title:'行程与住宿',items:['详细英文行程单','往返机票订单','全程酒店确认单（含姓名、日期、地址）','已购跨城火车票','德国停留天数说明附信']},
  {title:'资金与工作',items:['近3个月银行流水','在职证明英文版','营业执照复印件加盖公章','年假批准文件','工资单或完税证明（可选）']},
  {title:'保险与递交',items:['保额不少于€30,000的申根旅行保险','覆盖全程及所有申根国、医疗救援和遣返','预约VFS Global德国签证中心','准备签证费与VFS服务费','所有材料保留扫描件']},
]
