import { useEffect, useMemo, useState } from 'react'
import { AlertTriangle, Check, ChevronLeft, CircleDollarSign, CloudSun, Copy, ExternalLink, Languages, Luggage, Search, ShieldCheck, ShoppingBag, Smartphone, Stethoscope } from 'lucide-react'
import ExpenseLedger from './ExpenseLedger'
import { apps, glossary, packing, quickInfo, risks, shopping, visaGroups } from './toolboxData'
type Tool='home'|'expense'|'packing'|'visa'|'quick'|'apps'|'language'|'shopping'|'risks'
const tools=[['expense','费用分账',CircleDollarSign,'#27866b'],['packing','行李清单',Luggage,'#2f6feb'],['visa','签证材料',ShieldCheck,'#7c3aed'],['quick','应急速查',Stethoscope,'#e5484d'],['apps','常用App',Smartphone,'#0891b2'],['language','地名语言',Languages,'#8250df'],['shopping','购物退税',ShoppingBag,'#bf8700'],['risks','行程风险',AlertTriangle,'#e16f24']]as const
const toolGroups=[{id:'before',title:'出发前准备',note:'证件、装备与提前安装',mark:'🧳',tools:['packing','visa','apps','risks']},{id:'during',title:'旅途中使用',note:'记录、应急与现场查询',mark:'🧭',tools:['expense','quick','language','shopping']}]as const
const toolDescriptions:Record<Exclude<Tool,'home'>,string>={expense:'预算、消费与结算',packing:'出发前逐项勾选',visa:'申根材料逐项核对',quick:'天气、电话与支付',apps:'安装、登录与离线准备',language:'三语地名随手复制',shopping:'城市伴手礼与退税',risks:'高风险事项优先处理'}
const toolCopy:Record<Exclude<Tool,'home'>,{eyebrow:string;note:string;stamp:string}>={expense:{eyebrow:'TRIP WALLET',note:'预算、消费和同行结算都留在本机',stamp:'€'},packing:{eyebrow:'PACK & GO',note:'按场景收拾，比照着长清单更轻松',stamp:'✓'},visa:{eyebrow:'VISA FILE',note:'把申根材料整理成四个可核对文件袋',stamp:'VISA'},quick:{eyebrow:'POCKET GUIDE',note:'断网时也能快速找到的旅行常识',stamp:'SOS'},apps:{eyebrow:'PHONE KIT',note:'出发前安装并完成登录与离线下载',stamp:'APP'},language:{eyebrow:'SAY IT',note:'地名、交通和餐厅用语随手复制',stamp:'DE'},shopping:{eyebrow:'TAKE HOME',note:'按城市收藏值得带回家的小东西',stamp:'GIFT'},risks:{eyebrow:'PLAN B',note:'先处理红色事项，再看可现场应对项',stamp:'!'}}
const groupMarks:Record<string,string>={'证件与票据':'🛂','衣物':'🧥','电子设备':'🔌','随身小包':'🎒','身份与申请':'🪪','行程与住宿':'🗺️','资金与工作':'💳','保险与递交':'🛡️','九月底天气':'🌦️','紧急号码':'🆘','支付与现金':'💶','小费习惯':'☕','网络与插座':'📱','奥地利自驾':'🚗','安全与健康':'🩹','退税':'🧾','阿姆斯特丹':'🇳🇱','科隆':'🇩🇪','慕尼黑':'🥨','萨尔茨堡':'🇦🇹','维也纳':'🎻'}
const loadDone=()=>{try{return new Set<string>(JSON.parse(localStorage.getItem('travel-tool-done')||'[]'))}catch{return new Set<string>()}}
export default function Toolbox(){const [tool,setTool]=useState<Tool>('home');const [done,setDone]=useState(loadDone);const [query,setQuery]=useState('');const [copied,setCopied]=useState('');useEffect(()=>localStorage.setItem('travel-tool-done',JSON.stringify([...done])),[done]);const toggle=(id:string)=>setDone(old=>{const next=new Set(old);next.has(id)?next.delete(id):next.add(id);return next});const words=useMemo(()=>glossary.filter(item=>Object.values(item).join(' ').toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())),[query]);const copy=async(text:string)=>{await navigator.clipboard.writeText(text);setCopied(text);setTimeout(()=>setCopied(''),1000)}
 if(tool==='home')return <div className="tool-workspace"><header className="context-bar"><div><span>行前规划 · 旅途随身</span><b>工具</b></div></header><div className="tool-home-scroll">{toolGroups.map(group=><section className={`tool-phase tool-phase-${group.id}`} key={group.id}><header><i>{group.mark}</i><div><b>{group.title}</b><small>{group.note}</small></div><span>{group.tools.length} 项</span></header><div className="tool-tile-grid">{group.tools.map(toolId=>{const item=tools.find(([id])=>id===toolId);if(!item)return null;const [id,label,Icon,color]=item;return <button onClick={()=>setTool(id)} key={id}><span style={{'--tool':color} as React.CSSProperties}><Icon/></span><b>{label}</b><small>{toolDescriptions[id]}</small></button>})}</div></section>)}<section className="tool-glance"><CloudSun/><div><b>九月底天气</b><span>约7–19°C · 多风阵雨 · 分层穿衣</span></div><button onClick={()=>setTool('quick')}>查看</button></section></div></div>
 const title=tools.find(item=>item[0]===tool)?.[1]||'工具';const current=tools.find(item=>item[0]===tool);const currentColor=current?.[3]||'#337c67';const currentIcon=current?.[2]||Luggage;const checklist=tool==='packing'?packing:tool==='visa'?visaGroups:[];const total=checklist.reduce((sum,group)=>sum+group.items.length,0);const prefix=tool==='packing'?'pack':'visa';const completed=checklist.reduce((sum,group)=>sum+group.items.filter((_,index)=>done.has(`${prefix}-${'group' in group?group.group:group.title}-${index}`)).length,0);return <div className="tool-workspace"><header className="context-bar tool-context"><button onClick={()=>setTool('home')}><ChevronLeft/></button><div><span>工具</span><b>{title}</b></div></header><div className="tool-panel">
 <ToolHero tool={tool} title={title} Icon={currentIcon} color={currentColor} completed={completed} total={total}/>
 {tool==='expense'&&<><div className="budget-mini"><article><span>两人可变支出</span><b>待租车报价</b></article><article><span>自驾四天</span><b>租车+异地费待询</b></article><article><span>景点</span><b>约€200–260</b></article><article><span>餐饮</span><b>约€550</b></article></div><ExpenseLedger/></>}
 {tool==='quick'&&<div className="info-compact">{quickInfo.map((group,index)=><article style={{'--group-index':index} as React.CSSProperties} key={group.title}><h3><i>{groupMarks[group.title]||'✦'}</i>{group.title}</h3>{group.items.map(item=><p key={item}>{item}</p>)}</article>)}</div>}
 {tool==='packing'&&<CheckGroups groups={packing.map(group=>({title:group.group,items:group.items,prefix:'pack'}))} done={done} toggle={toggle}/>}
 {tool==='visa'&&<CheckGroups groups={visaGroups.map(group=>({title:group.title,items:group.items,prefix:'visa'}))} done={done} toggle={toggle}/>}
 {tool==='apps'&&<div className="app-compact">{apps.map((item,index)=><a style={{'--app-index':index} as React.CSSProperties} href={item.url} target="_blank" rel="noreferrer" key={item.name}><span className="app-icon"><i aria-hidden="true">{item.fallback}</i><img src={`${import.meta.env.BASE_URL}${item.icon}`} alt="" loading="lazy" onError={event=>{event.currentTarget.hidden=true}}/></span><div><b>{item.name}</b><small>{item.description}</small></div><ExternalLink/></a>)}</div>}
 {tool==='language'&&<><label className="tool-search"><Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="搜索中文、英文或当地名称"/></label><div className="language-compact">{words.map(item=>{const localLabel=item.country==='NL'?'荷兰语':'德语';const flag=item.country==='NL'?'🇳🇱':item.country==='DE'?'🇩🇪':'🇦🇹';return <article key={`${item.country}-${item.zh}`}><span>{flag} {item.category}</span><div><b>{item.zh}</b><small><i>{localLabel}</i>{item.local}</small><small><i>英语</i>{item.english}</small></div><button onClick={()=>copy(item.local)} aria-label={`复制${item.local}`} title="复制当地名称">{copied===item.local?<Check/>:<Copy/>}</button></article>})}</div></>}
 {tool==='shopping'&&<div className="info-compact shopping">{shopping.map((group,index)=><article style={{'--group-index':index} as React.CSSProperties} key={group.city}><h3><i>{groupMarks[group.city]||'🛍️'}</i>{group.city}</h3>{group.items.map(item=><p key={item}>{item}</p>)}</article>)}</div>}
 {tool==='risks'&&<div className="risk-compact">{risks.map((risk,index)=><article key={risk[1]} className={`risk-${risk[0]}`}><span>{risk[0]}</span><div><b>{risk[1]}</b><p>{risk[2]}</p></div><em>{index+1}</em></article>)}</div>}
 </div></div>}
function ToolHero({tool,title,Icon,color,completed,total}:{tool:Exclude<Tool,'home'>;title:string;Icon:typeof Luggage;color:string;completed:number;total:number}){const copy=toolCopy[tool];const progress=total?Math.round(completed/total*100):undefined;return <section className="tool-hero" style={{'--hero':color} as React.CSSProperties}><span className="tool-hero-icon"><Icon/></span><div><small>{copy.eyebrow}</small><h2>{title}</h2><p>{copy.note}</p>{progress!==undefined&&<div className="tool-progress"><i style={{width:`${progress}%`}}/><span>{completed}/{total} · {progress}%</span></div>}</div><em>{copy.stamp}</em></section>}
function CheckGroups({groups,done,toggle}:{groups:{title:string;items:string[];prefix:string}[];done:Set<string>;toggle:(id:string)=>void}){return <div className="check-compact">{groups.map((group,groupIndex)=>{const count=group.items.filter((_,index)=>done.has(`${group.prefix}-${group.title}-${index}`)).length;return <section style={{'--group-index':groupIndex} as React.CSSProperties} key={group.title}><header><i>{groupMarks[group.title]||'✦'}</i><div><b>{group.title}</b><small>{count===group.items.length?'这一袋收好了':'逐项点击确认'}</small></div><span>{count}/{group.items.length}</span></header><div className="group-progress"><i style={{width:`${Math.round(count/group.items.length*100)}%`}}/></div>{group.items.map((item,index)=>{const id=`${group.prefix}-${group.title}-${index}`;return <button className={done.has(id)?'done':''} onClick={()=>toggle(id)} key={item}><span>{done.has(id)&&<Check/>}</span><b>{item}</b></button>})}</section>})}</div>}
