export const quickInfo = [
  {title:'每日天气（出发前7天更新）',items:['9/25 阿姆斯特丹：当前尚未进入可靠逐日预报窗口；先按约11–18°C、多风阵雨准备','9/26 羊角村/阿姆斯特丹：水乡风力和阵雨会明显影响租船；先准备防水外套，最终看临行预报','9/27 阿姆斯特丹：博物馆日，按约11–18°C分层穿衣；雨天不影响室内主线','9/28 科隆：约9–18°C、早晚偏凉；大教堂和老城步行带防雨层','9/29 菲森/慕尼黑：约8–17°C；玛丽安桥山谷体感更冷，城堡段穿防滑鞋','9/30 慕尼黑/萨尔茨堡：约8–18°C；转场日带轻薄防水外套','10/1 萨尔茨堡/圣沃尔夫冈：湖区约7–17°C，湖船和湖边风大，早晚加中层','10/2 圣沃尔夫冈/哈尔施塔特：约7–16°C，雨雾会降低湖景能见度；公交返程不要压缩缓冲','10/3 戈绍湖/维也纳：湖区约6–16°C、山区更冷；低能见度时缩短湖畔停留','10/4 维也纳：约10–19°C；美景宫和老城步行，晚间音乐会备薄外套','10/5 维也纳：约10–19°C；返程日前按实际预报决定是否游美泉宫花园','提示：以上是季节性行程参考，不是实时预报；9/18起每天刷新，9/25–10/5以出发前7天逐日预报为准']},
  {title:'每日穿衣指数与出片指南',items:['9/25 阿姆斯特丹｜穿衣★★★☆☆：长袖T恤＋薄外套；史基浦到酒店夜间加围巾。出片：用运河灯光作背景，外套敞开露出亮色内搭。','9/26 羊角村｜穿衣★★★★☆：防水外套＋针织中层＋防滑鞋；船上风大，别穿长裙。出片：米色/燕麦色外套配水道和茅草屋，站在桥边拍侧身。','9/27 阿姆斯特丹博物馆日｜穿衣★★★☆☆：舒适长裤、薄针织、轻便鞋；室内外温差用可收纳外套解决。出片：博物馆广场用低饱和蓝灰穿搭，人物与建筑留出空间。','9/28 科隆｜穿衣★★★☆☆：长袖＋防风外套＋舒适步行鞋；大教堂内偏凉。出片：红棕或深蓝上衣在大教堂和霍亨索伦大桥形成稳重对比。','9/29 菲森/慕尼黑｜穿衣★★★★☆：保暖中层、防风外套、防滑鞋；玛丽安桥优先保暖，啤酒节再加围巾。出片：城堡段用米白、卡其或深绿，避开高跟鞋和拖地衣物。','9/30 慕尼黑→萨尔茨堡｜穿衣★★★☆☆：分层穿搭，薄羽绒或防水壳放在随身包；转场日优先轻便。出片：慕尼黑皇宫用干净的黑白或酒红配色，避免大行李入镜。','10/1 萨尔茨堡/圣沃尔夫冈｜穿衣★★★★☆：针织衫＋防风防水外套＋可走路的鞋；湖船上加一层。出片：米拉贝尔花园用浅色上衣，湖边用红/橙小面积点色。','10/2 圣沃尔夫冈/哈尔施塔特｜穿衣★★★★☆：保暖中层、防雨外套、抓地力好的鞋；雨雾天准备帽子。出片：湖畔选酒红、深绿或焦糖色，和木屋、山水更协调。','10/3 戈绍湖/维也纳｜穿衣★★★★☆：湖区按低温准备，防水鞋和帽子优先；到维也纳后可脱外层。出片：戈绍湖用简洁深色外套突出山湖，维也纳换围巾或耳饰增加城市感。','10/4 维也纳｜穿衣★★★☆☆：白天衬衫/薄针织＋轻外套，音乐会准备一件稍正式外套。出片：美景宫适合黑白、藏蓝或酒红；晚场避免运动鞋和过度休闲卫衣。','10/5 维也纳返程｜穿衣★★★☆☆：舒适分层、鞋子优先；把外套和证件放随身包。出片：美泉宫花园用浅色上衣和简洁长裤，兼顾行李移动与拍照。']},
  {title:'紧急号码',items:['欧盟通用急救/报警：112','荷兰警察非紧急：0900-8844','德国警察：110 · 急救/消防：112','奥地利警察：133 · 急救：144']},
  {title:'支付与现金',items:['全程两人建议随身备用现金€150–200；不是预算上限，主要用于小额和备用','建议分成两处携带：日常钱包€60–80，另一处备用€90–120；不要把全部现金放同一钱包','荷兰/德国/奥地利大多数酒店、铁路、博物馆和餐厅可刷Visa/Mastercard或手机钱包；交通优先OVpay/电子票','羊角村组合票线上购买后，火车、70路公交和1小时游船不需要再准备船票现金；小店、厕所、储物柜和临时打车准备€5/10/20小钞','德国啤酒节、市场和奥地利湖区小店更可能需要现金；餐厅小费按总额支付，预留约€20–30机动小费','带两张不同银行的卡，分开放；需要取现时用银行ATM，拒绝DCC动态换汇，选择以欧元结算']},
  {title:'小费习惯',items:['荷兰餐厅服务好可给5–10%，非强制','德国餐厅通常凑整或给5–10%','奥地利餐厅约5–10%，报总额而非把零钱留桌上','酒店行李员：€1–2/件']},
  {title:'网络与插座',items:['三国均使用欧标Type C/F，电压230V','中国两脚扁插通常需要转换头','建议购买欧盟通用eSIM，提前下载离线地图','跨城列车Wi-Fi不稳定，车票截图离线保存']},
  {title:'预约与票务（按最新行程）',items:['9/26 羊角村组合票：约€52–53/人，含荷兰火车往返Steenwijk、RRReis 70路公交往返和1小时游船；周六全天可用，游船通常11:00–15:00，不能用270路替代','9/26 安妮之家16:30–16:45：只能在线预约指定时间，Museumkaart也需单独预约；提前15分钟到，早到/迟到不能按普通开放时间入场','9/27 梵高09:00：已预约，票面允许开始后最多30分钟入场；必须携带Museumkaart和二维码','9/27 国立博物馆14:00–15:00：已预约；Museumkaart也必须预约start time，入馆后可留到17:00','9/29 新天鹅堡13:50：城堡套票不等于免预约；选择Multi-Day Ticket Holder并支付€2.50预约费，迟到通常不能补入','10/4 美景宫上宫：建议提前预约上午时段；10/5 美泉宫：按票面时段进入，最晚入场规则另看官方票面','SchafbergBahn高山小火车：按车次购票，错过已选班次要看余位改签；湖船、公交按当日班次衔接']},
  {title:'待预订优先级与风险',items:['P0｜立即锁定：新天鹅堡14天城堡套票/预约费、9/29回程FlexBus备选、10/1 SchafbergBahn上午车次；这些一旦没位会直接破坏当天主线','P1｜尽快锁定：9/26羊角村组合票、10/4美景宫上宫、10/5美泉宫；按当前行程选择官网票面时间，不要把酒店或交通误归到景点预约','P2｜入住前邮件确认：Holiday Inn Salzburg City的Guest Mobility Ticket；酒店可以提前发，但不是自动保证，入住时仍需核验姓名、日期和二维码','P3｜可现场决定：Salzburg Card、10/4晚音乐会回流票、啤酒节入棚；Salzburg Card只在要塞、出生地、游船等付费景点累计达到票价时才值得买','最大风险：早到/迟到的定时景点可能拒绝入场；高山小火车和湖区公交错过一班会连锁影响后续；FlexBus和火车不是同一张票，不能用拜仁日票覆盖']},
  {title:'逐项操作清单（两位30岁成人）',items:['P0｜新天鹅堡：打开官方售票页→选择9/29→选择13:50英文场→票种选Multi-Day Ticket Holder→每人支付预约费；14天套票另按官方渠道购买，二者不是同一张订单。预约成功后保存二维码、确认号和入场地址；至少提前30分钟到Hohenschwangau，不要把13:50理解成到菲森时间','P0｜SchafbergBahn：打开官方购票页→选择10/1→先选上午上山车次→再配下山车次；支付前截图显示的取消/改签条件。入住Hotel Weisser Bär时出示Wolfgangsee Card，购票前问清是否有折扣；不要先买无法改签的晚车再倒推湖船','P0｜9/29菲森返程：先查DB区域列车和FlexBus两套方案，优先锁定可退改的FlexBus备选；确认上车点、行李限制和最晚检票时间。FlexBus不受Bayern-Ticket覆盖，不能把两张票当一张用','P1｜羊角村组合票：在Discover Holland选择9/26周六、2位成人并核对姓名；确认组合票包含NS往返、RRReis 70路和1小时游船。付款后保存电子票；游船通常11:00–15:00，不能把“有组合票”理解成任意时段都能上船','P1｜Museumkaart与安妮之家：9/26先去伦勃朗故居现场买Museumkaart，再用安妮之家官网确认16:30–16:45预约并支付€1；购卡小票、卡号和安妮之家二维码分开保存。16:15前到入口，早到或迟到都可能无法按普通开放时间补入','P1｜美景宫上宫：打开Upper Belvedere官方售票页→选择10/4上午时段→两位成人→如持可用卡则按票面选择对应票种；付款前确认是Upper Belvedere而非Lower Belvedere。保存入场时段，不要只保存付款截图','P1｜美泉宫：打开官方售票页→选择10/5具体时段→按票面提示提前到入口；宫殿内参观受时段约束，花园不等于宫殿门票。不要用“当天开放”替代预约时段','P2｜萨尔茨堡Guest Mobility Ticket：现在就给Holiday Inn Salzburg City发邮件，提供订单号、两位姓名、入住日期，询问能否提前发数字票、有效期和流动性费；收到后核对是否覆盖抵达/离开交通。它是交通票，不是Salzburg Card，不含景点入场','P2｜Wolfgangsee Card：入住Hotel Weisser Bär时主动索取并拍下卡面/有效期；买船票和SchafbergBahn前先问参与商户折扣。不要默认它能替代Guest Mobility Ticket，也不要默认覆盖跨州火车','P2｜Bad Ischl/Sommercard：入住Sandwirt时询问当地Guest Card和Salzkammergut SommerCard的资格、价格、有效期及541/542/543公交覆盖；一晚住宿不保证免费，未得到酒店确认前按普通票预算','P3｜Salzburg Card：先列出要塞、莫扎特出生地、游船等真正要去的付费项目，再把单买总价与24/48小时卡价比较；只去老城、花园和免费项目时不买。Guest Mobility Ticket不能抵扣Salzburg Card','P3｜全程交通优惠：荷兰段先比较NS Off-peak Group Ticket、PrijsTijd Deal与OVpay；德国9/29用Bayern-Ticket去菲森，回程FlexBus另购；奥地利短途不买Vorteilscard，优先Sparschiene/普通票。每次付款前核对乘车日期、起点终点和是否可退改','执行顺序：今天先锁P0并发两封酒店邮件→收到确认后锁P1→入住前3–7天再次核对营业时间、班次和余票→出发前把二维码、订单号、酒店回复和备用路线下载到手机离线文件夹']},
  {title:'萨尔茨堡两张卡怎么区分',items:['Guest Mobility Ticket：过夜客因住宿登记获得，通常入住时由酒店发PDF或数字票；公共交通抵达可邮件提前索取，覆盖萨尔茨堡州公共交通，含住宿期间的抵达/离开交通','Guest Mobility Ticket不包含景点门票，且不应默认覆盖萨尔茨堡州外的圣沃尔夫冈、哈尔施塔特和维也纳；跨州段按ÖBB/公交官方票另买','Salzburg Card：自费购买的景点卡，2026年4月–10月成人24/48/72小时为€38/45/49；含市内景点一次免费入场及部分交通优惠，和Guest Mobility Ticket不是一回事','本行程只住萨尔茨堡市1晚，先用Guest Mobility Ticket解决市内/州内交通；是否买Salzburg Card，等确认要塞、莫扎特出生地和游船等项目后再核算']},
  {title:'湖区住宿卡与可用优惠',items:['10/1圣沃尔夫冈：住Hotel Weisser Bär时主动索取Wolfgangsee Card；官方说明住参与住宿商1晚以上即可免费领取，卡内优惠会随季节变化，合作项目包括Wolfgangsee Schifffahrt、SchafbergBahn等，先在窗口出示卡再买票','10/1圣沃尔夫冈：Guest Mobility Ticket和Wolfgangsee Card不是一张卡；交通时必须出示Guest Mobility Ticket，Wolfgangsee Card主要看折扣和活动','10/2巴德伊舍：入住Hotel & Hostel Sandwirt时索取当地Guest Card，并问是否能领取Salzkammergut SommerCard；官方夏卡在5月1日–10月31日有效，少于3晚通常不是免费卡，可能按€4.90/人购买','10/3戈绍湖/哈尔施塔特：不要把圣沃尔夫冈或萨尔茨堡的Guest Mobility Ticket带到上奥地利继续当通票；先按当天541/542/543公交规则购票或向酒店确认Guest Card覆盖范围','没有发现可验证的长期通用优惠码；最稳妥的优惠来自住宿卡、官方组合票、Bayern-Ticket和官网早鸟/可退改票，第三方“折扣码”不要作为行程成立条件']},
  {title:'全程两位成人优惠清单',items:['荷兰博物馆：Museumkaart对梵高、国立、伦勃朗故居和安妮之家最有价值；安妮之家仍必须单独网上预约并支付€1预约费，博物馆卡不保证有票','荷兰铁路：9/26组合票已覆盖羊角村段；其他荷兰铁路可比较NS Off-peak Group Ticket（2–3人当前€38.50总价）、NS PrijsTijd Deal（提前购买、非高峰最多约6折）和OVpay原价。9/25史基浦接酒店、9/27市内/返程要逐段核算，不为一次短程购买月票','德国：9/29两人Bayern-Ticket当前€44，工作日09:00后适用于区域交通；不覆盖FlexBus、ICE/IC长途或新天鹅堡门票。9/28科隆→慕尼黑已购票，不再重复买Deutschlandticket','科隆：当前只安排大教堂、桥和老城，不建议买Köln MuseumsCard；它适合连续看多个市立博物馆，成人单人€18且仅首日含市内交通','慕尼黑：当前只保留皇宫和啤酒节，München Card/Munich City Pass大概率不划算；官方City Pass成人从€39.90起，只有连续刷多个收费景点才考虑','奥地利铁路：两位30岁成人不要买ÖBB Vorteilscard Classic作为本次短途临时卡，年费€73/人，通常回本不了；提前买Sparschiene或比较普通票即可','维也纳：Vienna City Card 24小时€19、48小时€31、72小时€37，Discounts Only€9；本行程景点不多，先算美景宫/美泉宫/市内交通总价再决定。Vienna PASS从€109起且不含公共交通，更不适合当前轻量安排','排除项：学生、青年、65岁以上、残障、家庭/儿童票、当地居民卡和需要特定会员资格的优惠均不计入本次方案']},
  {title:'给Holiday Inn Salzburg City的邮件模板',items:['Subject: Request for Guest Mobility Tickets before check-in – 30 September 2026','Dear Holiday Inn Salzburg City team,\nWe have a confirmed reservation for 30 September 2026 (confirmation no. #20924100) for two guests. We will arrive by public transport and would like to ask whether you can issue the Salzburg Guest Mobility Tickets in advance by email or via digital wallet before check-in.\nGuest names: [姓名1], [姓名2]\nCould you please confirm the applicable mobility fee, the validity period, and whether the tickets cover our arrival from Munich and departure from Salzburg? We understand that the ticket is valid only within the Province of Salzburg.\nThank you very much.\nBest regards,\n[姓名]']},
  {title:'给湖区酒店的邮件模板',items:['Subject: Guest cards and transport benefits for our stay – October 2026','Dear Hotel Weisser Bär / Hotel & Hostel Sandwirt team,\nWe have a confirmed reservation for two guests: [酒店名称] from [入住日期] to [退房日期]. Could you please confirm which guest cards we are entitled to receive at check-in?\nFor St. Wolfgang, could you please confirm whether the free Wolfgangsee Card is available for a one-night stay, whether it provides a discount for SchafbergBahn or Wolfgangsee boat tickets, and whether the Guest Mobility Ticket can be issued before arrival?\nFor Bad Ischl, could you please confirm whether a local guest card or the Salzkammergut SommerCard is available for our one-night stay, its price, and whether it covers or discounts buses 541/542/543, Hallstatt or Gosausee attractions?\nPlease also let us know whether the card can be sent by email before check-in.\nThank you very much.\nBest regards,\n[姓名]']},
  {title:'奥地利无车湖区（10/1–10/3）',items:['10/1 萨尔茨堡→圣吉尔根：150/150X公交后接沃尔夫冈湖船；船班衔接不上时改经Strobl公交','10/2 圣沃尔夫冈→Bad Ischl→Hallstatt：高山小火车后乘公交，哈尔施塔特只安排湖畔，不赶盐矿','10/3 退房后把行李寄存在Hotel Garni Sandwirt，轻装去戈绍湖；15:30前取行李，保证17:31 IC 1119','Hallstatt Bahnhof在湖对岸；本次不走火车+渡轮主线，避免与Bad Ischl住宿和公交路线混淆','湖区公交/船班较稀疏，错过一班就缩短景点，不要为多看一处冒险压缩返程']},
  {title:'安全与健康',items:['中央站、地铁和热门景点注意手机与钱包','护照原件贴身，云端另存证件与保单副本','随身备止泻、感冒、胃药及个人常用药','饮用水通常安全；餐厅自来水不一定免费']},
  {title:'退税',items:['满足单店最低消费后向商户索取退税单','离开欧盟时在维也纳机场先海关验货盖章','托运行李中的退税商品要在托运前办理海关','再到Global Blue或Planet柜台退款']},
]

export const packing = [
  {group:'证件与票据',items:['护照及申根签证','旅行保险英文保单','机票、火车票离线截图','酒店确认单','哈尔施塔特火车与渡轮时刻截图','银行卡2张分开放','少量欧元现金']},
  {group:'衣物',items:['防水轻薄外套','针织衫/抓绒中层','长裤2–3条','舒适防滑步行鞋','轻便手套与薄围巾','折叠伞']},
  {group:'电子设备',items:['手机与充电线','欧标转换插头','充电宝（随身携带）','eSIM/漫游方案','耳机','备用数据线']},
  {group:'随身小包',items:['纸巾与湿巾','水杯','常用药','创可贴','小袋零食','酒店名片/地址截图']},
]

export const apps = [
  {name:'Google Maps',category:'地图与交通',description:'全程地图、公交与步行导航',url:'https://www.google.com/maps/?api=1',iosScheme:'comgooglemaps://',ios:'https://apps.apple.com/app/google-maps/id585027354',android:'https://play.google.com/store/apps/details?id=com.google.android.apps.maps',icon:'app-icons/google-maps.png',fallback:'GM'},
  {name:'NS',category:'地图与交通',description:'荷兰火车实时班次',url:'https://www.ns.nl/en',ios:'https://apps.apple.com/app/ns-travel-planner/id370362301',android:'https://play.google.com/store/apps/details?id=nl.ns.android.activity',icon:'app-icons/ns.png',fallback:'NS'},
  {name:'9292',category:'地图与交通',description:'荷兰综合公共交通',url:'https://9292.nl/en',ios:'https://apps.apple.com/app/9292-travel-planner-e-ticket/id556557690',android:'https://play.google.com/store/apps/details?id=nl.negentwee',icon:'app-icons/9292.png',fallback:'92'},
  {name:'DB Navigator',category:'地图与交通',description:'德国铁路、站台和延误',url:'https://int.bahn.de/en',iosScheme:'https://www.bahn.de/buchung/start',ios:'https://apps.apple.com/app/db-navigator/id343555245',android:'https://play.google.com/store/apps/details?id=de.hafas.android.db',icon:'app-icons/db-navigator.png',fallback:'DB'},
  {name:'MVV-App',category:'地图与交通',description:'慕尼黑市内交通',url:'https://www.mvv-muenchen.de/en',ios:'https://apps.apple.com/app/mvv-app/id388686726',android:'https://play.google.com/store/apps/details?id=com.mdv.companion',icon:'app-icons/mvv.png',fallback:'MV'},
  {name:'ÖBB',category:'地图与交通',description:'奥地利铁路、哈尔施塔特与维也纳车票',url:'https://www.oebb.at/en/',ios:'https://apps.apple.com/app/%C3%B6bb-tickets/id1041401604',android:'https://play.google.com/store/apps/details?id=at.oebb.ts',icon:'app-icons/oebb.png',fallback:'ÖB'},
  {name:'ASFINAG',category:'地图与交通',description:'奥地利高速票车牌查询与路况',url:'https://www.asfinag.at/en/',ios:'https://apps.apple.com/app/asfinag/id453459323',android:'https://play.google.com/store/apps/details?id=at.asfinag.unterwegs',icon:'app-icons/asfinag.png',fallback:'AS'},
  {name:'WienMobil',category:'地图与交通',description:'维也纳公共交通',url:'https://www.wienerlinien.at/web/wl-en',ios:'https://apps.apple.com/app/wienmobil/id1107918142',android:'https://play.google.com/store/apps/details?id=at.wienerlinien.wienmobillab',icon:'app-icons/wienmobil.png',fallback:'WM'},
  {name:'Google Translate',category:'语言沟通',description:'菜单与现场沟通',url:'https://translate.google.com',ios:'https://apps.apple.com/app/google-translate/id414706506',android:'https://play.google.com/store/apps/details?id=com.google.android.apps.translate',icon:'app-icons/google-translate.png',fallback:'GT'},
  {name:'DeepL',category:'语言沟通',description:'德语长句翻译',url:'https://www.deepl.com',ios:'https://apps.apple.com/app/deepl-translate/id1552407475',android:'https://play.google.com/store/apps/details?id=com.deepl.mobiletranslator',icon:'app-icons/deepl.png',fallback:'DL'},
  {name:'Global Blue',category:'旅行服务',description:'退税进度查询',url:'https://www.globalblue.com/',ios:'https://apps.apple.com/app/global-blue-shop-tax-free/id693120896',android:'https://play.google.com/store/apps/details?id=com.buuuk.globalblue',icon:'app-icons/global-blue.ico',fallback:'GB'},
  {name:'Splitwise',category:'旅行服务',description:'额外的多人分账备份',url:'https://www.splitwise.com/',ios:'https://apps.apple.com/app/splitwise/id458023433',android:'https://play.google.com/store/apps/details?id=com.Splitwise.SplitwiseMobile',icon:'app-icons/splitwise.png',fallback:'SW'},
]

export const shopping = [
  {city:'阿姆斯特丹',items:['Tony’s Chocolonely巧克力','荷兰奶酪（真空包装）','Royal Delft蓝陶小件','HEMA设计文具','郁金香主题纪念品（注意入境植物限制）']},
  {city:'科隆',items:['4711古龙水旅行装','科隆大教堂纪念品','Kölsch细长啤酒杯','当地巧克力']},
  {city:'慕尼黑',items:['啤酒节纪念杯与徽章','Haribo限定口味','巴伐利亚传统小饰品','Dallmayr咖啡与茶']},
  {city:'萨尔茨堡',items:['莫扎特巧克力球','Zaunerstollen杏仁糕','岩盐制品','《音乐之声》纪念品']},
  {city:'维也纳',items:['Manner威化','Demel/Sacher甜点礼盒','Julius Meinl咖啡','奥地利水晶或博物馆文创']},
]

export const glossary = [
  {zh:'阿姆斯特丹',local:'Amsterdam',english:'Amsterdam',country:'NL',category:'城市'},
  {zh:'史基浦机场',local:'Luchthaven Schiphol',english:'Amsterdam Airport Schiphol',country:'NL',category:'机场'},
  {zh:'阿姆斯特丹斯洛特戴克站',local:'Station Amsterdam Sloterdijk',english:'Amsterdam Sloterdijk Station',country:'NL',category:'车站'},
  {zh:'阿姆斯特丹中央站',local:'Amsterdam Centraal',english:'Amsterdam Central Station',country:'NL',category:'车站'},
  {zh:'斯滕韦克',local:'Steenwijk',english:'Steenwijk',country:'NL',category:'城市'},
  {zh:'羊角村',local:'Giethoorn',english:'Giethoorn',country:'NL',category:'景点'},
  {zh:'九街',local:'De 9 Straatjes',english:'The Nine Streets',country:'NL',category:'街区'},
  {zh:'安妮之家',local:'Anne Frank Huis',english:'Anne Frank House',country:'NL',category:'景点'},
  {zh:'伦勃朗故居',local:'Museum Rembrandthuis',english:'Rembrandt House Museum',country:'NL',category:'博物馆'},
  {zh:'梵高博物馆',local:'Van Gogh Museum',english:'Van Gogh Museum',country:'NL',category:'博物馆'},
  {zh:'荷兰国立博物馆',local:'Rijksmuseum',english:'Rijksmuseum',country:'NL',category:'博物馆'},
  {zh:'荷兰博物馆卡',local:'Museumkaart',english:'Netherlands Museum Card',country:'NL',category:'票务'},
  {zh:'约旦区',local:'Jordaan',english:'Jordaan',country:'NL',category:'街区'},
  {zh:'阿姆斯特丹斯洛特戴克智选假日酒店',local:'Holiday Inn Express Amsterdam – Sloterdijk',english:'Holiday Inn Express Amsterdam – Sloterdijk',country:'NL',category:'住宿'},

  {zh:'科隆',local:'Köln',english:'Cologne',country:'DE',category:'城市'},
  {zh:'科隆中央站',local:'Köln Hauptbahnhof / Köln Hbf',english:'Cologne Central Station',country:'DE',category:'车站'},
  {zh:'科隆大教堂',local:'Kölner Dom',english:'Cologne Cathedral',country:'DE',category:'景点'},
  {zh:'霍亨索伦大桥',local:'Hohenzollernbrücke',english:'Hohenzollern Bridge',country:'DE',category:'景点'},
  {zh:'莱茵河',local:'Rhein',english:'Rhine River',country:'DE',category:'地标'},
  {zh:'科隆老城',local:'Kölner Altstadt',english:'Cologne Old Town',country:'DE',category:'街区'},
  {zh:'路德维希博物馆',local:'Museum Ludwig',english:'Museum Ludwig',country:'DE',category:'博物馆'},
  {zh:'科隆希尔顿酒店',local:'Hilton Köln',english:'Hilton Cologne',country:'DE',category:'住宿'},
  {zh:'慕尼黑',local:'München',english:'Munich',country:'DE',category:'城市'},
  {zh:'慕尼黑东站',local:'München Ostbahnhof',english:'Munich East Station',country:'DE',category:'车站'},
  {zh:'慕尼黑中央站',local:'München Hauptbahnhof / München Hbf',english:'Munich Central Station',country:'DE',category:'车站'},
  {zh:'玛利亚广场',local:'Marienplatz',english:'Marienplatz',country:'DE',category:'景点'},
  {zh:'新市政厅钟琴',local:'Rathaus-Glockenspiel',english:'New Town Hall Glockenspiel',country:'DE',category:'景点'},
  {zh:'慕尼黑圣母教堂',local:'Frauenkirche München',english:'Munich Cathedral',country:'DE',category:'景点'},
  {zh:'维克图阿连市场',local:'Viktualienmarkt',english:'Viktualienmarkt Food Market',country:'DE',category:'市场'},
  {zh:'慕尼黑皇宫与珍宝馆',local:'Münchner Residenz und Schatzkammer',english:'Munich Residenz and Treasury',country:'DE',category:'景点'},
  {zh:'英国花园',local:'Englischer Garten',english:'English Garden',country:'DE',category:'公园'},
  {zh:'艾斯巴赫冲浪点',local:'Eisbachwelle',english:'Eisbach Wave',country:'DE',category:'景点'},
  {zh:'慕尼黑皇家啤酒屋',local:'Hofbräuhaus München',english:'Hofbräuhaus Munich',country:'DE',category:'餐厅'},
  {zh:'慕尼黑啤酒节／特蕾西娅草坪',local:'Oktoberfest / Theresienwiese',english:'Oktoberfest / Theresienwiese',country:'DE',category:'活动'},
  {zh:'慕尼黑东站慕奇夕酒店',local:'Moxy München Ostbahnhof',english:'Moxy Munich Ostbahnhof',country:'DE',category:'住宿'},
  {zh:'菲森',local:'Füssen',english:'Fussen',country:'DE',category:'城市'},
  {zh:'新天鹅堡',local:'Schloss Neuschwanstein',english:'Neuschwanstein Castle',country:'DE',category:'景点'},
  {zh:'玛丽安桥',local:'Marienbrücke',english:"Mary's Bridge",country:'DE',category:'景点'},
  {zh:'拜仁日票',local:'Bayern-Ticket',english:'Bavaria Regional Day Ticket',country:'DE',category:'票务'},
  {zh:'FlexBus',local:'FlixBus',english:'FlixBus',country:'DE',category:'交通'},

  {zh:'萨尔茨堡',local:'Salzburg',english:'Salzburg',country:'AT',category:'城市'},
  {zh:'霍亨萨尔茨堡要塞',local:'Festung Hohensalzburg',english:'Hohensalzburg Fortress',country:'AT',category:'景点'},
  {zh:'莫扎特出生地',local:'Mozarts Geburtshaus',english:"Mozart's Birthplace",country:'AT',category:'景点'},
  {zh:'萨尔茨堡老城',local:'Salzburger Altstadt',english:'Salzburg Old Town',country:'AT',category:'街区'},
  {zh:'粮食胡同',local:'Getreidegasse',english:'Getreidegasse',country:'AT',category:'街区'},
  {zh:'米拉贝尔花园',local:'Mirabellgarten',english:'Mirabell Gardens',country:'AT',category:'景点'},
  {zh:'圣吉尔根',local:'St. Gilgen',english:'St Gilgen',country:'AT',category:'城市'},
  {zh:'沃尔夫冈湖',local:'Wolfgangsee',english:'Lake Wolfgang',country:'AT',category:'湖区'},
  {zh:'圣沃尔夫冈',local:'St. Wolfgang im Salzkammergut',english:'St Wolfgang im Salzkammergut',country:'AT',category:'城市'},
  {zh:'巴德伊舍',local:'Bad Ischl',english:'Bad Ischl',country:'AT',category:'城市'},
  {zh:'巴德伊舍火车站',local:'Bad Ischl Bahnhof',english:'Bad Ischl station',country:'AT',category:'车站'},
  {zh:'圣沃尔夫冈高山小火车',local:'SchafbergBahn',english:'Schafberg Railway',country:'AT',category:'景点'},
  {zh:'哈尔施塔特',local:'Hallstatt',english:'Hallstatt',country:'AT',category:'城市'},
  {zh:'哈尔施塔特市场广场',local:'Marktplatz Hallstatt',english:'Hallstatt Market Square',country:'AT',category:'景点'},
  {zh:'哈尔施塔特骨屋',local:'Beinhaus Hallstatt',english:'Hallstatt Bone House',country:'AT',category:'景点'},
  {zh:'前戈绍湖',local:'Vorderer Gosausee',english:'Lake Gosau / Vorderer Gosausee',country:'AT',category:'湖区'},
  {zh:'戈绍',local:'Gosau',english:'Gosau',country:'AT',category:'城市'},
  {zh:'巴德戈伊瑟恩',local:'Bad Goisern am Hallstättersee',english:'Bad Goisern on Lake Hallstatt',country:'AT',category:'城市'},
  {zh:'高山小火车',local:'SchafbergBahn',english:'Schafberg Railway',country:'AT',category:'交通'},
  {zh:'戈绍湖',local:'Vorderer Gosausee',english:'Lake Gosau',country:'AT',category:'湖区'},
  {zh:'维也纳',local:'Wien',english:'Vienna',country:'AT',category:'城市'},
  {zh:'维也纳中央站',local:'Wien Hauptbahnhof / Wien Hbf',english:'Vienna Central Station',country:'AT',category:'车站'},
  {zh:'美景宫上宫',local:'Oberes Belvedere',english:'Upper Belvedere',country:'AT',category:'博物馆'},
  {zh:'维也纳音乐之友协会',local:'Musikverein Wien',english:'Vienna Musikverein',country:'AT',category:'演出'},
  {zh:'格拉本大街',local:'Graben',english:'Graben',country:'AT',category:'街区'},
  {zh:'圣史蒂芬大教堂',local:'Stephansdom',english:"St. Stephen's Cathedral",country:'AT',category:'景点'},
  {zh:'美泉宫',local:'Schloss Schönbrunn',english:'Schönbrunn Palace',country:'AT',category:'景点'},
  {zh:'维也纳美泉宫希尔顿逸林酒店',local:'DoubleTree by Hilton Vienna Schönbrunn',english:'DoubleTree by Hilton Vienna Schönbrunn',country:'AT',category:'住宿'},
  {zh:'维也纳国际机场',local:'Flughafen Wien-Schwechat',english:'Vienna International Airport',country:'AT',category:'机场'},

  {zh:'中央火车站',local:'Hauptbahnhof / Hbf',english:'Central Station',country:'DE',category:'交通'},
  {zh:'站台',local:'Gleis',english:'Platform',country:'DE',category:'交通'},
  {zh:'换乘',local:'Umsteigen',english:'Transfer / Change trains',country:'DE',category:'交通'},
  {zh:'行李寄存柜',local:'Schließfach',english:'Luggage locker',country:'DE',category:'交通'},
  {zh:'特价票',local:'Super Sparpreis',english:'Super saver fare',country:'DE',category:'交通'},
  {zh:'区域列车',local:'Regionalbahn / Regional-Express',english:'Regional train',country:'DE',category:'交通'},
  {zh:'请问站台在哪里？',local:'Wo ist das Gleis?',english:'Where is the platform?',country:'DE',category:'应急'},
  {zh:'这班车去……吗？',local:'Fährt dieser Zug nach …?',english:'Does this train go to …?',country:'DE',category:'应急'},
  {zh:'请结账',local:'Zahlen, bitte.',english:'The bill, please.',country:'DE',category:'餐厅'},
  {zh:'不要再续杯',local:'Bitte nicht mehr.',english:'No more, please.',country:'DE',category:'餐厅'},
]

export const risks = [
  ['高','新天鹅堡时段必须预约','持14天套票仍需选择Multi-Day Ticket Holder并支付预约费；13:50前到入口，迟到通常不能补入。'],['高','9/28科隆至慕尼黑换乘2次','当天持续查看DB App；前序延误时保留原票并按DB指引改乘。'],['高','9/29菲森返程衔接紧','13:50导览结束后立即下山；15:20火车不稳就切换FlexBus，不为啤酒节冒险。'],['中','D1羊角村接安妮之家','返程延误就取消九街和其他弹性安排；16:30–16:45安妮之家预约优先，伦勃朗故居只保留购卡动作。'],['中','D2取行李到发车缓冲有限','18:20开始返回Sloterdijk取行李，19:50前到阿姆斯特丹中央站。'],['中','慕尼黑至萨尔茨堡票种限制','拜仁日票只覆盖区域列车，不含Railjet和ICE；9/29回程FlexBus另购。'],['中','Moxy两晚是两个订单','首次入住时请前台关联，尽量原房续住。'],
  ['高','湖区公交与渡轮衔接','150/150X和Hallstatt渡轮班次需在出发前复核，错过一班就压缩弹性活动。'],['高','26寸行李不随一日游移动','萨尔茨堡连续住3晚；若酒店不能寄存，改用萨尔茨堡Hbf储物柜。'],['中','Hallstatt Bahnhof不在古城','火车到站后必须衔接约15分钟渡轮，返程至少预留一班船的缓冲。'],['中','萨尔茨堡→维也纳直达车票','提前订座并确认行李架，避免带大箱换乘区域列车。'],['中','湖区雨雾与早霜','每日查天气；低能见度时缩短湖畔散步，优先按原路返回。'],['中','哈尔施塔特盐矿复开时间','2026夏季计划重开但日期未锁定，只作为可选项，临行复核。'],['低','连续多日同酒店','每天只整理随身日包，护照、药品和电子设备不要交给寄存柜。'],['低','维也纳返程日不要再绕市区','13:30取行李，15:00直接前往机场。'],
]

export const visaGroups = [
  {title:'身份与申请',items:['德国申根签证申请表并签字','护照原件及资料页/签证页复印件','旧护照（如有）','身份证和户口簿复印件','近期35×45mm白底照片×2']},
  {title:'行程与住宿',items:['详细英文行程单','往返机票订单','全程酒店确认单（含姓名、日期、地址）','已购跨城火车票','德国停留天数说明附信']},
  {title:'资金与工作',items:['近3个月银行流水','在职证明英文版','营业执照复印件加盖公章','年假批准文件','工资单或完税证明（可选）']},
  {title:'保险与递交',items:['保额不少于€30,000的申根旅行保险','覆盖全程及所有申根国、医疗救援和遣返','预约VFS Global德国签证中心','准备签证费与VFS服务费','所有材料保留扫描件']},
]
