import { useEffect, useRef, useState } from 'react'
import { ExternalLink, Layers3, Maximize2 } from 'lucide-react'
import { dayMaps, modeColors } from './mapData'

declare global{interface Window{L:any}}

export default function TripMap({dayId,activeId,onSelect}:{dayId:string;activeId?:string;onSelect:(id:string)=>void}){
  const host=useRef<HTMLDivElement>(null);const mapRef=useRef<any>(null);const layerRef=useRef<any>(null);const tileRef=useRef<any>(null)
  const [domestic,setDomestic]=useState(false);const [full,setFull]=useState(false)
  const data=dayMaps[dayId]
  useEffect(()=>{if(!host.current||!window.L||mapRef.current)return;const L=window.L;mapRef.current=L.map(host.current,{zoomControl:true,attributionControl:true}).setView(data.center,data.zoom);return()=>{mapRef.current?.remove();mapRef.current=null}},[])
  useEffect(()=>{const map=mapRef.current;if(!map||!window.L)return;const L=window.L;if(tileRef.current)map.removeLayer(tileRef.current);tileRef.current=domestic?L.tileLayer('https://webrd0{s}.is.autonavi.com/appmaptile?lang=zh_en&size=1&scale=1&style=7&x={x}&y={y}&z={z}',{subdomains:'1234',attribution:'© 高德地图',maxZoom:18}):L.tileLayer('https://{s}.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}{r}.png',{subdomains:'abcd',attribution:'© OpenStreetMap © CARTO',maxZoom:19});tileRef.current.addTo(map)},[domestic])
  useEffect(()=>{const map=mapRef.current;if(!map||!window.L)return;const L=window.L;if(layerRef.current)map.removeLayer(layerRef.current);const group=L.layerGroup();layerRef.current=group;const coords=data.points.map(point=>[point.lat,point.lng]);data.points.forEach((point,index)=>{const color=modeColors[point.mode];const active=point.activityId===activeId;const icon=L.divIcon({className:'trip-map-icon',html:`<div style="--marker:${color}" class="map-marker ${active?'active':''}">${index+1}</div>`,iconSize:[active?34:28,active?34:28],iconAnchor:[active?17:14,active?17:14]});const marker=L.marker([point.lat,point.lng],{icon}).bindTooltip(`${index+1}. ${point.label}`,{direction:'top',offset:[0,-10]});marker.on('click',()=>onSelect(point.activityId));marker.addTo(group)});for(let index=1;index<data.points.length;index++){const from=data.points[index-1],to=data.points[index];L.polyline([[from.lat,from.lng],[to.lat,to.lng]],{color:modeColors[to.mode],weight:3,dashArray:to.mode==='walk'?'3 7':'9 6',opacity:.78}).addTo(group)}if(data.hotel){const icon=L.divIcon({className:'trip-map-icon',html:'<div class="hotel-marker">⌂</div>',iconSize:[30,30],iconAnchor:[15,15]});L.marker([data.hotel.lat,data.hotel.lng],{icon,zIndexOffset:800}).bindTooltip(data.hotel.label).addTo(group);coords.push([data.hotel.lat,data.hotel.lng])}group.addTo(map);if(coords.length>1)map.fitBounds(L.latLngBounds(coords),{padding:[32,32],maxZoom:14,animate:false});else map.setView(data.center,data.zoom);setTimeout(()=>map.invalidateSize(),60)},[dayId,activeId,data,onSelect])
  useEffect(()=>{const map=mapRef.current;if(!map||!host.current||!window.ResizeObserver)return;const L=window.L;const coords=data.points.map(point=>[point.lat,point.lng]);if(data.hotel)coords.push([data.hotel.lat,data.hotel.lng]);const observer=new ResizeObserver(()=>{map.invalidateSize();if(coords.length>1)map.fitBounds(L.latLngBounds(coords),{padding:[34,34],maxZoom:14,animate:false})});observer.observe(host.current);return()=>observer.disconnect()},[dayId,data])
  const selected=data.points.find(point=>point.activityId===activeId)
  return <section className={`trip-map-shell ${full?'full':''}`}><div ref={host} className="trip-map"/><div className="map-actions"><button onClick={()=>setDomestic(value=>!value)} title={`切换至${domestic?'国际':'国内'}底图`}><Layers3/>{domestic?'国内底图':'国际底图'}</button><button onClick={()=>setFull(value=>!value)} title="全屏地图"><Maximize2/></button></div><div className="map-legend"><span><i className="drive"/>自驾</span><span><i className="train"/>火车</span><span><i className="walk"/>步行</span><span><i className="sight"/>景点</span></div>{selected&&<a className="map-navigate" target="_blank" rel="noreferrer" href={`https://www.google.com/maps/search/?api=1&query=${selected.lat},${selected.lng}`}><ExternalLink/>导航到{selected.label}</a>}</section>
}
